services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"          
    volumes:
      - ./frontend:/app 
      - /app/node_modules
    working_dir: /app
    command: npm run dev

  server:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
    depends_on:
      - pocketbase

  pocketbase:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    volumes:
      - ./backend/pb_data:/pb_data